server:
  port: 9100
spring:
  application:
    name: cq-message
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.157.111:8848
      config:
        server-addr: 192.168.157.111:8848
        file-extension: yml
        #prefix: addr-test
    stream:
      rocketmq:
        binder:
          access-key: ShtAdmin
          secret-key: ShtAdmin_4399_ss
          name-server: 47.108.29.138:13000
      bindings:
        output:
          destination: stream-test-topic


